import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: '/landing', pathMatch: 'full' },
  { path: 'landing', loadComponent: () => import('./components/landing/landing-home/landing-home.component').then(m => m.LandingHomeComponent) },
  { path: 'about', loadComponent: () => import('./components/landing/about/about.component').then(m => m.AboutComponent) },
  { path: 'services', loadComponent: () => import('./components/landing/services/services.component').then(m => m.ServicesComponent) },
  { path: 'blog', loadComponent: () => import('./components/landing/blog/blog.component').then(m => m.BlogComponent) },
  { path: 'brand-guidelines', loadComponent: () => import('./components/brand/brand-guidelines/brand-guidelines.component').then(m => m.BrandGuidelinesComponent) },
  { path: 'login', loadComponent: () => import('./components/landing/auth/auth.component').then(m => m.AuthComponent) },
  { path: 'dashboard', loadComponent: () => import('./components/dashboard/dashboard-layout/dashboard-layout.component').then(m => m.DashboardLayoutComponent),
    children: [
      { path: 'patient/home', loadComponent: () => import('./components/patient/patient-dashboard/patient-dashboard.component').then(m => m.PatientDashboardComponent) },
      { path: 'patient/appointments', loadComponent: () => import('./components/patient/appointment-booking/appointment-booking.component').then(m => m.AppointmentBookingComponent) },
      { path: 'patient/records', loadComponent: () => import('./components/patient/medical-records/medical-records.component').then(m => m.MedicalRecordsComponent) },
      { path: 'patient/ai-chat', loadComponent: () => import('./components/patient/ai-chat/ai-chat.component').then(m => m.AiChatComponent) },
      { path: 'patient/billing', loadComponent: () => import('./components/patient/billing-history/billing-history.component').then(m => m.BillingHistoryComponent) },
      { path: 'patient/pharmacy', loadComponent: () => import('./components/patient/pharmacy-orders/pharmacy-orders.component').then(m => m.PharmacyOrdersComponent) },
      { path: 'patient/prescriptions', loadComponent: () => import('./components/patient/prescription-flow/prescription-flow.component').then(m => m.PrescriptionFlowComponent) },
      { path: 'patient/pricing', loadComponent: () => import('./components/landing/pricing/pricing.component').then(m => m.PricingComponent) },
      { path: 'doctor/home', loadComponent: () => import('./components/doctor/doctor-dashboard/doctor-dashboard.component').then(m => m.DoctorDashboardComponent) },
      { path: 'doctor/patients', loadComponent: () => import('./components/doctor/patient-list/patient-list.component').then(m => m.PatientListComponent) },
      { path: 'doctor/appointments', loadComponent: () => import('./components/doctor/doctor-scheduler/doctor-scheduler.component').then(m => m.DoctorSchedulerComponent) },
      { path: 'doctor/consultations', loadComponent: () => import('./components/doctor/consultation/consultation.component').then(m => m.ConsultationComponent) },
      { path: 'doctor/financial', loadComponent: () => import('./components/doctor/doctor-financial/doctor-financial.component').then(m => m.DoctorFinancialComponent) },
      { path: 'lab/home', loadComponent: () => import('./components/lab/lab-dashboard/lab-dashboard.component').then(m => m.LabDashboardComponent) },
      { path: 'lab/results', loadComponent: () => import('./components/lab/lab-result-entry/lab-result-entry.component').then(m => m.LabResultEntryComponent) },
      { path: 'lab/payroll', loadComponent: () => import('./components/lab/lab-payroll/lab-payroll.component').then(m => m.LabPayrollComponent) },
      { path: 'pharmacy/home', loadComponent: () => import('./components/pharmacy/pharmacy-dashboard/pharmacy-dashboard.component').then(m => m.PharmacyDashboardComponent) },
      { path: 'pharmacy/delivery', loadComponent: () => import('./components/pharmacy/delivery-management/delivery-management.component').then(m => m.DeliveryManagementComponent) },
      { path: 'pharmacy/wallet', loadComponent: () => import('./components/pharmacy/pharmacy-wallet/pharmacy-wallet.component').then(m => m.PharmacyWalletComponent) },
      { path: 'admin/home', loadComponent: () => import('./components/admin/admin-dashboard/admin-dashboard.component').then(m => m.AdminDashboardComponent) },
      { path: 'admin/users', loadComponent: () => import('./components/admin/user-management/user-management.component').then(m => m.UserManagementComponent) },
      { path: 'admin/verifications', loadComponent: () => import('./components/admin/doctor-verification/doctor-verification.component').then(m => m.DoctorVerificationComponent) },
      { path: 'admin/financials', loadComponent: () => import('./components/admin/financial-admin/financial-admin.component').then(m => m.FinancialAdminComponent) },
      { path: 'admin/payroll', loadComponent: () => import('./components/admin/payroll-management/payroll-management.component').then(m => m.PayrollManagementComponent) },
      { path: 'admin/settings', loadComponent: () => import('./components/admin/admin-settings/admin-settings.component').then(m => m.AdminSettingsComponent) },
      { path: '', redirectTo: 'patient/home', pathMatch: 'full' },
    ]
  },
  { path: '**', redirectTo: '/landing' },
];
